## KNN - K-Nearest Neighbors

In [17]:
# K-Nearest Neighbors (KNN) is a simple and popular supervised machine learning algorithm used for both classification and regression problems.
# The basic idea is:

# "Similar data points are likely to belong to the same category."

# When a new data point arrives, KNN finds the K nearest neighbors (existing data points) and makes a prediction based on them.

### How KNN Works

In [18]:
# # Step 1: Choose the value of K
# # K represents the number of nearest neighbors to consider.
# # Example:

# # K = 3 → consider the 3 closest points
# # K = 5 → consider the 5 closest points

# # Step 2: Calculate Distance
# # Measure the distance between the new point and all training data points.

# Step 3: Find K Nearest Neighbors
# Sort all distances and select the K smallest distances.

# Step 4: Make Prediction
# For Classification
# Use majority voting.

# For Regression
# Take the average of the K nearest values.

### Example

In [19]:
# Example
# Suppose we want to classify whether a fruit is an Apple or Orange.
# Training Data

# Weight (g)         Color Score        Fruit
# 150                    7              Apple
# 170                    8              Apple
# 130                    5              Orange 
# 120                    4              Orange

# New Fruit:
# Weight = 160 g
# Color Score = 7

# If K = 3:
# Nearest neighbors might be:

# If K = 3:
# Nearest neighbors might be:

# Neighbor          Fruit
# 150,7             Apple
# 170,8             Apple
# 130,5             Orange
# Majority = Apple
# Prediction: Apple

In [20]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

In [21]:
df = pd.read_csv('Titanic.csv')
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [23]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [24]:
#Filling Missing values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

#Encode Categorical Variable
Le = LabelEncoder()
df['Sex'] = Le.fit_transform(df['Sex'])

df = pd.get_dummies(df,columns=['Embarked'],drop_first=True)

#Dropping The column that not used in model training
df = df.drop(columns=['Name','Cabin','Ticket',"PassengerId"])
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         0       3    1  22.0      1      0   7.2500       False        True
1         1       1    0  38.0      1      0  71.2833       False       False
2         1       3    0  26.0      0      0   7.9250       False        True
3         1       1    0  35.0      1      0  53.1000       False        True
4         0       3    1  35.0      0      0   8.0500       False        True

In [25]:
X = df.drop('Survived',axis=1)
y = df['Survived']

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [27]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,precision_score,recall_score
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [28]:
Knn = KNeighborsClassifier(n_neighbors=5,weights='uniform',algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=None)
Knn.fit(X_train_scaled,y_train)
knn_pred = Knn.predict(X_test_scaled)
knn_result = {
    'Accuracy':accuracy_score(y_test,knn_pred),
    'Precision':precision_score(y_test,knn_pred),
    'Recall':recall_score(y_test,knn_pred)
}
knn_result

{'Accuracy': 0.8156424581005587,
 'Precision': 0.78125,
 'Recall': 0.7246376811594203}

In [29]:
comparison_df = pd.DataFrame({
    'KNN':knn_result
}).T.round(2)

comparison_df

     Accuracy  Precision  Recall
KNN      0.82       0.78    0.72