### SVM (Support Vector Machine)

In [ ]:
#Support Vector Machine (SVM) is a supervised machine learning algorithm used for classification and regression tasks. It tries to find the best boundary known as hyperplane that separates different classes in the data. 

#The main goal of SVM is to maximize the margin between the two classes. The larger the margin the better the model performs on new and unseen data.

### Key Concepts

- **Hyperplane**: A decision boundary separating different classes in feature space and is represented by the equation wx + b = 0 in linear classification.

- **Support Vectors**:The closest data points to the hyperplane, crucial for determining the hyperplane and margin in SVM.

- **Margin**:The distance between the hyperplane and the support vectors. SVM aims to maximize this margin for better classification performance.

- **Kernal**:A function that maps data to a higher-dimensional space enabling SVM to handle non-linearly separable data.

- **Hard Margin**:A maximum-margin hyperplane that perfectly separates the data without misclassifications.

- **Soft Margin**:Allows some misclassifications by introducing slack variables, balancing margin maximization and misclassification penalties when data is not perfectly separable.

- **C**: A regularization term balancing margin maximization and misclassification penalties. A higher C value forces stricter penalty for misclassifications.

- **Hinge Loss**: A loss function penalizing misclassified points or margin violations and is combined with regularization in SVM.

- **Dual Problem**: Involves solving for Lagrange multipliers associated with support vectors, facilitating the kernel trick and efficient computation.

#### import the libraries

In [15]:
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv('Titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder


df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

df = pd.get_dummies(df,columns=['Embarked'],drop_first=True)

#Dropping unwated column 
df = df.drop(columns=['Cabin','Name','Ticket','PassengerId'])

df

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,0,3,1,22.0,1,0,7.2500,False,True
1,1,1,0,38.0,1,0,71.2833,False,False
2,1,3,0,26.0,0,0,7.9250,False,True
3,1,1,0,35.0,1,0,53.1000,False,True
4,0,3,1,35.0,0,0,8.0500,False,True
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,13.0000,False,True
887,1,1,0,19.0,0,0,30.0000,False,True
888,0,3,0,28.0,1,2,23.4500,False,True
889,1,1,1,26.0,0,0,30.0000,False,False
890,0,3,1,32.0,0,0,7.7500,True,False

### Train/Split Data

In [22]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,precision_score,recall_score

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)  # stratify = y used to preserve the distibution in dataset for train and test

In [27]:
sc = StandardScaler()
X_train_Scaled = sc.fit_transform(X_train)
X_test_Scaled = sc.fit_transform(X_test)

In [ ]:
from sklearn.svm import SVC

Svm = SVC(kernel='rbf',random_state=42)
Svm.fit(X_train_Scaled,y_train)
svm_pred = Svm.predict(X_test_Scaled)

Svm_result = {
    'Accuracy':accuracy_score(y_test,svm_pred),
    'Precision':precision_score(y_test,svm_pred),
    'Recall':recall_score(y_test,svm_pred),
}

In [32]:
svm_df = pd.DataFrame([Svm_result], index=['SVM']).round(4)
svm_df

     Accuracy  Precision  Recall
SVM    0.8045     0.8269  0.6232