## Week 4 — Build First Machine Learning Model

Build a classification model
Steps:
* Split dataset
##### Train model using:
* Logistic Regression
* Decision Tree
##### Evaluate using:
* Accuracy
* Confusion matrix

In [36]:
import pandas as pd

##### Load Dataset

In [37]:
df = pd.read_csv('Housing.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

##### Dataset Summary

In [38]:
print("="*50)
print("Dataset Info")
print("="*50)
df.info()

==================================================
Dataset Info
==================================================
<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [39]:
print("="*50)
print("Statistical summary")
print("="*50)
df.describe()

==================================================
Statistical summary
==================================================

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

##### Datatype Analysis

In [40]:
print("="*50)
print("Data type Analysis")
print("="*50)
report_type = pd.DataFrame({
    'columns': df.columns,
    'Data Type': df.dtypes.values,
    'Non-Empty Count': df.notnull().sum().values,
    'Empty count': df.isnull().sum().values,
    'unique values':df.nunique().values
})
print(report_type.to_string(index=False))

==================================================
Data type Analysis
==================================================
         columns Data Type  Non-Empty Count  Empty count  unique values
           price     int64              545            0            219
            area     int64              545            0            284
        bedrooms     int64              545            0              6
       bathrooms     int64              545            0              4
         stories     int64              545            0              4
        mainroad       str              545            0              2
       guestroom       str              545            0              2
        basement       str              545            0              2
 hotwaterheating       str              545            0              2
 airconditioning       str              545            0              2
         parking     int64              545            0              4
        prefarea       str              545            0              2
furnishingstatus       str              545            0              3

##### Missing Value Detection

In [41]:
print("Missing Value Detection: ")
df.isnull().sum()

Missing Value Detection:

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

#### Encode Categorical variable

In [45]:
#im going to use the label Encoder for this because all the categorical column has natural order
from sklearn.preprocessing import LabelEncoder

lr  = LabelEncoder()

df['mainroad'] = lr.fit_transform(df['mainroad'])
df['guestroom'] = lr.fit_transform(df['guestroom'])
df['basement'] = lr.fit_transform(df['basement'])
df['hotwaterheating'] = lr.fit_transform(df['hotwaterheating'])
df['airconditioning'] = lr.fit_transform(df['airconditioning'])
df['prefarea'] = lr.fit_transform(df['prefarea'])

#Explicitly map furnishing status to preserve logical order
#why im using the manual mappuinf for the furnishistatus is because it contain 3 furnished, semi-fur, un-fur 
#if we use label encoder it assign 0 1 2 to variable in alphabetical order so the un-fur - 2, semi-f-1 , fur -0 
# it will tricks our model into thinking that an unfurnished house (2) is "greater than" or worth more than a furnished house (0).
furnishing_map = {'unfurnished': 0, 'semi-furnished': 1, 'furnished': 2}
df['furnishingstatus'] = df['furnishingstatus'].map(furnishing_map)

In [44]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,2
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,2
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,2
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,2