# Week 2 — Data Cleaning & Preprocessing

Task
Using the same dataset:

* Handle missing values
* Remove duplicates
* Encode categorical variables
* Normalize numerical features

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('Yearly_EoP.csv')
df.head()

,Date,USD,EUR,JPY,GBP,CAD,CHF,INR,CNY,TRY,SAR,IDR,AED,THB,VND,EGP,KRW,RUB,ZAR,AUD
0,1978,226.0,137.1,NaN,110.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1979,512.0,299.1,"125,630.3",230.6,611.8,835.6,"4,189.6",NaN,NaN,"1,749.0","324,101.3","2,055.9","10,645.2",NaN,NaN,"253,615.9",NaN,434.1,474.3
2,1980,589.8,392.4,"119,823.1",246.7,703.7,"1,047.8","4,620.3",NaN,NaN,"1,960.1","367,506.8","2,149.9","12,026.7",NaN,NaN,"389,010.8",NaN,439.1,499.4
3,1981,397.5,327.5,"87,899.5",208.2,475.3,719.8,"3,625.1",NaN,NaN,"1,372.5","249,492.1","1,456.3","9,089.6",NaN,NaN,"280,200.1",NaN,383.1,355.0
4,1982,456.9,429.9,"105,366.4",282.5,551.2,899.8,"4,320.0",NaN,0.1,"1,543.1","310,012.9","1,642.3","10,240.0",NaN,NaN,"335,836.8",NaN,482.6,456.8

# Handling Missing Values

In [6]:
df.drop_duplicates(inplace=True)
df

,Date,USD,EUR,JPY,GBP,CAD,CHF,INR,CNY,TRY,SAR,IDR,AED,THB,VND,EGP,KRW,RUB,ZAR,AUD
0,1978,226.0,137.1,NaN,110.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1979,512.0,299.1,"125,630.3",230.6,611.8,835.6,"4,189.6",NaN,NaN,"1,749.0","324,101.3","2,055.9","10,645.2",NaN,NaN,"253,615.9",NaN,434.1,474.3
2,1980,589.8,392.4,"119,823.1",246.7,703.7,"1,047.8","4,620.3",NaN,NaN,"1,960.1","367,506.8","2,149.9","12,026.7",NaN,NaN,"389,010.8",NaN,439.1,499.4
3,1981,397.5,327.5,"87,899.5",208.2,475.3,719.8,"3,625.1",NaN,NaN,"1,372.5","249,492.1","1,456.3","9,089.6",NaN,NaN,"280,200.1",NaN,383.1,355.0
4,1982,456.9,429.9,"105,366.4",282.5,551.2,899.8,"4,320.0",NaN,0.1,"1,543.1","310,012.9","1,642.3","10,240.0",NaN,NaN,"335,836.8",NaN,482.6,456.8
5,1983,382.4,432.0,"88,442.8",263.5,474.5,831.9,"3,995.0",NaN,0.1,"1,334.4","380,175.3","1,368.8","8,699.7",NaN,NaN,"303,482.9",NaN,466.4,424.3
6,1984,308.3,402.5,"77,716.7",266.0,408.2,803.8,"3,825.9",NaN,0.1,"1,106.4","331,867.4","1,134.4","8,219.4",NaN,NaN,"255,666.7",NaN,612.8,374.1
7,1985,326.8,347.5,"65,490.6",226.1,457.2,673.6,"3,920.6","1,047.4",0.2,"1,193.6","366,475.7","1,196.7","8,614.4",NaN,NaN,"291,095.5",NaN,843.9,479.6
8,1986,388.8,337.8,"61,832.1",262.2,540.0,630.2,"5,061.0","1,430.9",0.3,"1,465.8","632,246.1","1,434.4","9,953.8",NaN,NaN,"333,768.3",NaN,851.2,587.4
9,1987,484.1,351.8,"58,714.4",257.7,629.5,616.8,"6,116.9","1,758.9",0.5,"1,820.3","776,608.7","1,781.5","11,789.2",NaN,NaN,"379,396.7",NaN,934.3,669.6
10,1988,410.3,332.7,"51,253.0",226.8,488.5,616.2,"6,123.1","1,516.9",0.8,"1,537.1","704,545.5","1,505.6","10,261.9",NaN,966.3,"277,911.2",NaN,976.1,479.8
11,1989,398.6,310.7,"57,287.2",247.2,461.6,614.9,"6,624.8","1,873.5",0.9,"1,490.3","715,762.5","1,459.4","10,036.1","1,800,931.7","1,018.4","269,064.4",NaN,"1,015.7",504.6
12,1990,386.2,265.7,"53,028.2",200.1,453.8,498.4,"6,948.9","2,039.2",1.1,"1,454.9","743,695.8","1,425.0","9,633.2","2,543,477.4","1,116.8","279,605.7",NaN,"1,000.3",506.5
13,1991,353.2,250.3,"44,151.4",188.8,408.5,478.8,"9,080.6","1,900.6",1.8,"1,321.0","706,524.6","1,293.7","8,922.8","4,586,186.2","1,171.1","268,147.8",NaN,968.5,465.1
14,1992,332.9,266.7,"41,576.2",219.9,425.3,487.8,"9,639.3","1,931.5",2.9,"1,249.8","685,837.3","1,224.0","8,436.2","3,611,720.4","1,108.5","262,056.7",NaN,"1,017.8",484.7
15,1993,391.8,348.2,"43,592.9",264.8,517.1,580.1,"12,252.6","2,265.5",5.8,"1,465.0","824,654.2","1,432.0","9,977.9","4,226,900.8","1,316.7","315,272.6",486.1,"1,327.2",575.5
16,1994,383.3,308.8,"38,236.9",245.0,537.6,501.6,"12,022.1","3,237.0",14.8,"1,437.7","842,383.5","1,407.6","9,621.5","4,243,700.5","1,306.4","302,192.6","1,374.9","1,358.4",494.1
17,1995,387.0,290.7,"39,921.0",249.3,527.8,445.3,"13,608.9","3,218.8",23.6,"1,451.4","884,875.5","1,421.4","9,748.5","4,261,810.8","1,317.2","300,215.3","1,788.8","1,410.8",520.2
18,1996,369.3,290.5,"42,858.8",215.8,506.1,495.8,"13,228.4","3,064.2",40.3,"1,385.0","872,353.1","1,356.0","9,467.6","4,068,831.3","1,252.8","312,200.9","2,063.7","1,727.2",464.9
19,1997,290.2,266.1,"37,733.3",176.4,415.3,423.3,"11,378.7","2,402.7",60.1,"1,088.4","1,594,648.7","1,065.8","13,973.1","3,567,035.9",987.4,"491,888.9","1,740.5","1,412.3",445.4
20,1998,287.8,245.1,"32,463.8",173.0,442.1,395.3,"12,230.4","2,382.7",90.8,"1,079.5","2,288,008.5","1,057.1","10,457.2","3,998,402.7",981.4,"346,079.3","6,202.1","1,693.1",469.2
21,1999,290.3,289.2,"29,756.4",179.8,421.6,464.2,"12,631.0","2,403.1",157.4,"1,088.5","2,046,262.5","1,066.1","10,906.1","4,071,917.3",992.9,"328,795.2","7,996.4","1,786.3",444.2
22,2000,274.5,296.2,"31,463.0",184.2,413.2,450.5,"12,815.4","2,271.9",183.9,"1,029.4","2,611,391.8","1,008.1","11,889.2","3,983,367.3","1,067.6","343,748.6","7,728.5","2,079.5",496.3
23,2001,276.5,312.9,"36,287.9",190.9,440.8,463.3,"13,345.3","2,288.6",400.5,"1,037.0","2,896,337.5","1,015.6","12,219.9","4,169,896.5","1,266.4","365,809.5","8,434.6","3,308.3",540.6
24,2002,347.2,331.4,"41,132.8",216.4,547.8,481.8,"16,643.0","2,873.9",570.7,"1,302.2","3,107,440.0","1,275.3","15,019.9","5,347,227.2","1,604.1","414,556.8","11,049.6","3,005.8",615.8
25,2003,416.3,332.0,"44,555.4",233.9,539.2,518.0,"18,953.9","3,445.2",584.3,"1,561.1","3,527,718.8","1,528.9","16,508.5","6,513,896.3","2,564.1","498,355.3","12,173.2","2,751.3",556.0
26,2004,435.6,319.4,"44,888.6",226.2,524.2,493.5,"19,046.6","3,605.2",586.1,"1,633.6","4,061,970.0","1,600.0","17,001.5","6,875,946.0","2,651.7","453,677.4","12,096.6","2,464.4",559.3
27,2005,513.0,433.2,"60,431.4",297.8,597.1,674.5,"23,168.4","4,140.4",692.6,"1,924.4","5,045,355.0","1,884.3","21,040.7","8,159,265.0","2,944.0","517,796.6","14,777.0","3,246.7",700.3
28,2006,632.0,480.0,"75,125.8",321.8,733.4,771.2,"27,991.3","4,938.5",894.5,"2,370.2","5,712,016.0","2,321.3","22,461.3","10,139,176.0","3,609.0","587,538.8","16,654.2","4,430.8",801.3
29,2007,833.8,566.7,"94,047.0",418.4,817.5,939.9,"32,878.9","6,089.8",977.0,"3,126.2","7,845,587.5","3,062.5","28,084.9","13,360,843.8","4,608.6","780,056.5","20,388.9","5,692.3",954.5
30,2008,869.8,616.2,"78,564.5",603.5,"1,060.5",919.0,"42,152.4","5,945.0","1,323.3","3,264.5","9,523,762.5","3,194.7","30,223.8","15,194,532.5","4,796.2","1,126,761.1","25,547.1","8,143.0","1,259.4"
31,2009,"1,087.5",758.4,"100,463.3",677.0,"1,147.3","1,127.1","50,846.1","7,422.5","1,641.6","4,078.9","10,254,037.5","3,994.6","36,300.8","20,090,475.0","5,967.2","1,266,393.8","32,961.6","8,033.6","1,215.4"
32,2010,"1,405.5","1,059.7","114,885.6",913.0,"1,407.3","1,316.8","63,022.6","9,277.4","2,184.4","5,270.8","12,621,390.0","5,162.4","42,375.8","27,400,222.5","8,158.9","1,588,186.9","42,966.1","9,367.5","1,388.3"
33,2011,"1,531.0","1,183.0","118,974.0",994.2,"1,564.2","1,441.7","81,150.7","9,672.1","2,935.2","5,741.7","13,829,523.0","5,623.2","48,655.2","32,186,213.0","9,238.4","1,770,494.3","49,161.6","12,531.2","1,511.4"
34,2012,"1,657.5","1,253.6","142,677.6","1,025.7","1,649.1","1,513.3","90,847.6","10,332.0","2,965.4","6,216.3","15,971,670.0","6,088.2","50,711.2","34,509,150.0","10,256.8","1,768,966.9","50,321.2","14,041.4","1,596.4"
35,2013,"1,204.5",872.8,"126,568.9",729.4,"1,282.7","1,069.0","74,461.6","7,302.4","2,555.0","4,517.6","14,725,012.5","4,424.1","39,542.5","25,418,563.5","8,359.6","1,270,747.5","39,741.2","12,565.7","1,350.6"
36,2014,"1,206.0",992.0,"144,068.8",775.2,"1,399.4","1,192.9","76,321.7","7,479.6","2,809.3","4,527.3","14,966,460.0","4,429.6","39,646.0","25,787,898.0","8,624.2","1,322,366.9","67,197.4","13,956.3","1,474.3"
37,2015,"1,060.0",971.5,"127,846.6",715.0,"1,472.2","1,049.4","70,437.5","6,881.5","3,098.9","3,979.2","14,696,900.0","3,893.4","38,228.9","23,812,900.0","8,298.2","1,248,870.8","77,838.2","16,495.0","1,455.0"
38,2016,"1,145.9","1,094.3","133,497.4",937.3,"1,548.5","1,173.5","77,866.8","7,965.0","4,032.4","4,299.7","15,442,148.4","4,208.9","41,147.0","26,097,872.5","20,772.9","1,382,872.1","69,252.1","15,592.5","1,590.0"
39,2017,"1,291.0","1,080.1","145,702.3",960.0,"1,625.6","1,263.0","82,694.4","8,434.6","4,871.2","4,841.9","17,465,939.0","4,741.7","42,104.7","29,319,901.0","22,941.7","1,383,022.5","74,337.9","15,995.9","1,657.3"
40,2018,"1,279.0","1,117.9","141,214.4","1,007.2","1,744.2","1,259.3","89,408.5","8,797.2","6,746.6","4,798.3","18,572,359.0","4,697.8","41,625.1","29,660,010.0","22,883.2","1,426,468.7","88,967.2","18,380.9","1,816.8"
41,2019,"1,514.8","1,351.1","164,941.1","1,154.6","1,978.3","1,466.4","107,975.2","10,583.3","9,001.6","5,682.1","21,076,231.5","5,563.7","45,380.4","35,099,787.0","24,312.8","1,752,808.1","93,899.4","21,307.7","2,163.9"
42,2020,"1,887.6","1,536.0","194,894.7","1,388.0","2,409.9","1,666.8","138,116.3","12,313.6","13,922.9","7,082.5","26,496,241.2","6,933.2","56,560.1","43,577,133.6","29,688.0","2,055,709.7","140,666.8","27,583.3","2,457.8"
43,2021,"1,805.9","1,596.0","207,997.8","1,339.1","2,308.2","1,651.3","134,486.2","11,509.0","23,924.1","6,781.5","25,762,256.1","6,632.9","60,194.4","41,160,739.1","28,362.5","2,151,363.3","134,714.2","28,815.2","2,490.1"
44,2022,"1,813.8","1,698.0","241,283.2","1,502.8","2,457.1","1,673.6","150,235.6","12,631.5","33,931.8","6,819.5","28,357,981.3","6,661.2","62,748.5","42,853,471.3","44,898.3","2,290,603.0","133,991.9","30,685.8","2,674.8"

In [9]:
df.isnull().sum()
df.shape

(45, 20)

In [14]:
d = df.dropna()

In [15]:
d.shape

(30, 20)

In [16]:
d.isnull().sum()

Date    0
USD     0
EUR     0
JPY     0
GBP     0
CAD     0
CHF     0
INR     0
CNY     0
TRY     0
SAR     0
IDR     0
AED     0
THB     0
VND     0
EGP     0
KRW     0
RUB     0
ZAR     0
AUD     0
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Load dataset
df = pd.read_csv("Yearly_EoP.csv", na_values=["#N/A"])

print("Original Shape:", df.shape)
print("*" *50)
print("1. Handle Missing Values")
print("*" *50)


# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"])

# Remove commas and convert numeric columns
for col in df.columns:
    if col != "Date":
        df[col] = pd.to_numeric(
            df[col].astype(str).str.replace(",", "", regex=False),
            errors="coerce"
        )

# Fill missing values with median
for col in df.columns:
    if col != "Date":
        df[col].fillna(df[col].median(), inplace=True)

print("*" *50)
print("2. Remove Duplicates")
print("*" *50)

duplicates_before = df.duplicated().sum()
df = df.drop_duplicates()

print("Duplicates Removed:", duplicates_before)

print("*" *50)
print("3. Encode Categorical Variables")
print("*" *50)

# Extract year from Date and use it as numerical feature
df["Year"] = df["Date"].dt.year

# Drop original Date column
df.drop("Date", axis=1, inplace=True)

print("*" *50)
print("4. Normalize Numerical Features")
print("*" *50)

scaler = MinMaxScaler()

numeric_columns = df.columns
df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

print("*" *50)
print(" Save Cleaned Dataset")
print("*" *50)

df.to_csv("Yearly_EoP_Cleaned.csv", index=False)

print("Cleaned dataset saved as 'Yearly_EoP_Cleaned.csv'")
print("Final Shape:", df.shape)
print(df.head())

Original Shape: (45, 20)
Duplicates Removed: 0
Cleaned dataset saved as 'Yearly_EoP_Cleaned.csv'
Final Shape: (45, 20)
        USD       EUR       JPY       GBP       CAD       CHF       INR  CNY  \
0  0.000000  0.000000       NaN  0.000000       NaN       NaN       NaN  NaN
1  0.172123  0.103786  0.453247  0.086129  0.099370  0.344442  0.003850  NaN
2  0.218946  0.163559  0.425793  0.097694  0.144224  0.510444  0.006788  NaN
3  0.103214  0.121981  0.274873  0.070038  0.032749  0.253853  0.000000  NaN
4  0.138962  0.187584  0.357449  0.123411  0.069794  0.394665  0.004740  NaN

   TRY       SAR       IDR       AED       THB  VND  EGP       KRW  RUB  \
0  NaN       NaN       NaN       NaN       NaN  NaN  NaN       NaN  NaN
1  NaN  0.118881  0.002654  0.176841  0.044486  NaN  NaN  0.000000  NaN
2  NaN  0.153756  0.004199  0.192706  0.069821  NaN  NaN  0.066468  NaN
3  NaN  0.056682  0.000000  0.075644  0.015958  NaN  NaN  0.013051  NaN
4  0.0  0.084866  0.002153  0.107036  0.037055  NaN  NaN  0.040364  NaN

        ZAR       AUD  Year
0       NaN       NaN   0.0
1  0.001683  0.051427   0.0
2  0.001848  0.062247   0.0
3  0.000000  0.000000   0.0
4  0.003284  0.043883   0.0

C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\DinakaranThiruvarasu\AppData\Local\Temp\ipykernel_14728\2910464958.py:28: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)