### Week 9 — Model Optimization

#### Task
Improve model performance using:
- Hyperparameter Tuning
- GridSearchCV

#### Deliverables

#### Model Performance Comparison

| Model | Before | After |
|---------|---------|---------|
| Model Name | Performance Score | Improved Score |

### Improvements
- Tuned model hyperparameters to achieve better performance.
- Used **GridSearchCV** to find the best parameter combination.
- Improved model accuracy and overall prediction quality.

## Skills Tested
- Model Optimization
- Hyperparameter Tuning
- GridSearchCV

### 1. Importing Libraries:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

### 2. Loading The Dataset:

In [2]:
df = pd.read_csv('tickets.csv')
df.head()

                                   text     category
0                          Cannot login  Login issue
1        Unable to log in to my account  Login issue
2              Login page keeps failing  Login issue
3    Forgot password and cannot sign in  Login issue
4  Incorrect username or password error  Login issue

### 3.Text Preprocessing:

In [4]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def clean_text(text):
    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Convert to lowercase
    text = text.lower()
    # Tokenize and lemmatize
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(token,pos='v') for token in tokens if token not in stopwords.words('english')]
    return ' '.join(tokens)

df['cleaned_text'] = df['text'].apply(clean_text)
df[['text', 'cleaned_text']].head()

                                   text                       cleaned_text
0                          Cannot login                       cannot login
1        Unable to log in to my account                 unable log account
2              Login page keeps failing               login page keep fail
3    Forgot password and cannot sign in        forget password cannot sign
4  Incorrect username or password error  incorrect username password error