# To load a csv File

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('monthly_sales.csv')
df.head() # to print first 5 records
df.tail() # to print last 5 records

      month region    product  units  price_per_unit
45  2024-11   East  Product_C     84           55.35
46  2024-11   East  Product_C     57           95.77
47  2024-11   East  Product_D    197           66.29
48  2024-12   West  Product_A    122           67.20
49  2024-12   East  Product_D     85           80.20

# To load a json File

In [9]:
df = pd.read_json('sample1.json')
df

    id        name    class  marks
0    1   Student 1  Class A     81
1    2   Student 2  Class B     72
2    3   Student 3  Class C     65
3    4   Student 4  Class A     90
4    5   Student 5  Class B     58
5    6   Student 6  Class C     76
6    7   Student 7  Class A     84
7    8   Student 8  Class B     69
8    9   Student 9  Class C     73
9   10  Student 10  Class A     62
10  11  Student 11  Class B     88
11  12  Student 12  Class C     91
12  13  Student 13  Class A     55
13  14  Student 14  Class B     79
14  15  Student 15  Class C     67
15  16  Student 16  Class A     82
16  17  Student 17  Class B     74
17  18  Student 18  Class C     63
18  19  Student 19  Class A     95
19  20  Student 20  Class B     61
20  21  Student 21  Class C     77
21  22  Student 22  Class A     89
22  23  Student 23  Class B     70
23  24  Student 24  Class C     64
24  25  Student 25  Class A     83
25  26  Student 26  Class B     56
26  27  Student 27  Class C     92
27  28  Student 28  Class A     68
28  29  Student 29  Class B     71
29  30  Student 30  Class C     60
30  31  Student 31  Class A     86
31  32  Student 32  Class B     78
32  33  Student 33  Class C     66
33  34  Student 34  Class A     93
34  35  Student 35  Class B     59
35  36  Student 36  Class C     80
36  37  Student 37  Class A     72
37  38  Student 38  Class B     65
38  39  Student 39  Class C     90
39  40  Student 40  Class A     57
40  41  Student 41  Class B     75
41  42  Student 42  Class C     88
42  43  Student 43  Class A     69
43  44  Student 44  Class B     81
44  45  Student 45  Class C     62
45  46  Student 46  Class A     85
46  47  Student 47  Class B     73
47  48  Student 48  Class C     94
48  49  Student 49  Class A     78
49  50  Student 50  Class B     64