### Week 6 — Feature Engineering
#### Task
- Create 3 new features
- Retrain model
- Compare results before and after
#### Deliverables
- Feature explanation
- Performance improvement analysis

### 1.Importing Libraries

In [14]:
import pandas as pd
import matplotlib.pyplot as plt

### 2.Load The Dataset

In [15]:
df = pd.read_csv('Titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 3.Data Preprocessing And EDA

In [16]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [17]:
#fill missng values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

#Encode categorical variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df = pd.get_dummies(df,columns=['Embarked'],drop_first=True)

#drop unwanted columns
df = df.drop(columns=['Name','Cabin','Ticket','PassengerId'])
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,0,3,male,22.0,1,0,7.2500,False,True
1,1,1,female,38.0,1,0,71.2833,False,False
2,1,3,female,26.0,0,0,7.9250,False,True
3,1,1,female,35.0,1,0,53.1000,False,True
4,0,3,male,35.0,0,0,8.0500,False,True

### 4.Split the dataset (Feature and Target Variable)