In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('Dataset_Sample.csv')
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

# Filtering = Keeping the rows that match a condition

In [20]:
# tall_pokemon = df[df["Height"]>=3]
# tall_pokemon
# heavy_pokemon = df[df['Weight']>=150]
# heavy_pokemon
# legendary_pokemon = df[df['Legendary'] ==True]
# legendary_pokemon
# water_pokemon = df[(df['Type1']=='Water')& (df['Type2'] == 'Poison')]
# water_pokemon
fire_pokemaon = df[(df['Type1']=='Fire')|(df['Type2']=='Flying')]
fire_pokemaon

      No        Name     Type1   Type2  Height  Weight  Legendary
3      4  Charmander      Fire     NaN     0.6     8.5          0
4      5  Charmeleon      Fire     NaN     1.1    19.0          0
5      6   Charizard      Fire  Flying     1.7    90.5          0
11    12  Butterfree       Bug  Flying     1.1    32.0          0
15    16      Pidgey    Normal  Flying     0.3     1.8          0
16    17   Pidgeotto    Normal  Flying     1.1    30.0          0
17    18     Pidgeot    Normal  Flying     1.5    39.5          0
20    21     Spearow    Normal  Flying     0.3     2.0          0
21    22      Fearow    Normal  Flying     1.2    38.0          0
36    37      Vulpix      Fire     NaN     0.6     9.9          0
37    38   Ninetales      Fire     NaN     1.1    19.9          0
40    41       Zubat    Poison  Flying     0.8     7.5          0
41    42      Golbat    Poison  Flying     1.6    55.0          0
57    58   Growlithe      Fire     NaN     0.7    19.0          0
58    59    Arcanine      Fire     NaN     1.9   155.0          0
76    77      Ponyta      Fire     NaN     1.0    30.0          0
77    78    Rapidash      Fire     NaN     1.7    95.0          0
82    83  Farfetch'd    Normal  Flying     0.8    15.0          0
83    84       Doduo    Normal  Flying     1.4    39.2          0
84    85      Dodrio    Normal  Flying     1.8    85.2          0
122  123     Scyther       Bug  Flying     1.5    56.0          0
125  126      Magmar      Fire     NaN     1.3    44.5          0
129  130    Gyarados     Water  Flying     6.5   235.0          0
135  136     Flareon      Fire     NaN     0.9    25.0          0
141  142  Aerodactyl      Rock  Flying     1.8    59.0          0
143  144    Articuno       Ice  Flying     1.7    55.4          1
144  145      Zapdos  Electric  Flying     1.6    52.6          1
145  146     Moltres      Fire  Flying     2.0    60.0          1
148  149   Dragonite    Dragon  Flying     2.2   210.0          0